/*
 * This file was auto-generated by Reshuffle
 *
 * It is used to mock the calls to the backend when developing locally.
 * Please keep it with your source control tool.
 * Please do not remove or change it manually.
 */
const { setupProxy } = require('@reshuffle/local-proxy');
module.exports = setupProxy(__dirname);
